INSERT INTO ekpompes (sid,name,rating)
    VALUES (1,'kalhmera','18');
INSERT INTO ekpompes (sid,name,rating)
    VALUES (2,'kalhnyxta','18');
INSERT INTO ekpompes (sid,name,rating)
    VALUES (3,'kalhspera','18');  

INSERT INTO account (username,pass)
    VALUES ('Peris', '1234');

SELECT
 CASE WHEN
  (VALUE.startDate BETWEEN t2.startDate AND t2.endDate) OR
  (VALUE.endDate BETWEEN t2.startDate AND t2.endDate) OR
  (VALUE.startDate < t2.startDate AND VALUE.endDate > t2.endDate) OR
  (VALUE.startDate > t2.startDate AND VALUE.endDate < t2.endDate)
 THEN
  'yes'
 ELSE
  'no'
 END AS OverLapping
from TaskPeriods AS t2


INSERT INTO account (username,pass)
    VALUES ('thanasis', '1234');  