CREATE OR REPLACE FUNCTION "staff"()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
    BEGIN
    drop table IF EXISTS staff;
    create table IF NOT EXISTS staff
    (
        staff_id SERIAL,
        sector enum(`empty`,`etc`) default empty,
        specialty enum(`empty`,`etc`) default empty,
        age varchar(2) ,
        phone_number varchar(14) ,
        primary key(staff_id)
    );
    END;
$function$
