CREATE OR REPLACE FUNCTION "ekpompes"()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
    BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'rating') then 
    create type rating as enum('K' ,'8','12', '16','18')  ;END IF;
    drop table IF EXISTS ekpompes;
    create table IF NOT EXISTS ekpompes
    (
        sid int,
        name varchar(20),
        rating rating,
        primary key(sid)
    );
    END;
$function$
